using AgentOrchestrator.CodeQuality;

namespace AgentOrchestrator.CodeQuality.Tests;

public sealed class RepositoryHierarchyBuilderTests : IDisposable
{
    private readonly string root = Path.Combine(Path.GetTempPath(), $"quality-studio-{Guid.NewGuid():N}");

    [Fact]
    public void DerivesAllFiveLevelsFromDotNetSources()
    {
        Directory.CreateDirectory(Path.Combine(root, "src", "Demo"));
        File.WriteAllText(Path.Combine(root, "Demo.slnx"),
            "<Solution><Project Path=\"src/Demo/Demo.csproj\" /></Solution>");
        File.WriteAllText(Path.Combine(root, "src", "Demo", "Demo.csproj"),
            "<Project Sdk=\"Microsoft.NET.Sdk\" />");
        File.WriteAllText(Path.Combine(root, "src", "Demo", "Greeter.cs"),
            "namespace Demo.Greetings; public sealed class Greeter\n{\n    public string SayHello() => \"hello\";\n}");

        var project = Assert.Single(RepositoryHierarchyBuilder.BuildDotNet(root));
        var module = Assert.Single(project.Children);
        var ns = Assert.Single(module.Children);
        var file = Assert.Single(ns.Children);
        var function = Assert.Single(file.Children);

        Assert.Equal(ReviewLevel.Project, project.Level);
        Assert.Equal("Demo.Greetings", ns.Name);
        Assert.NotEqual(module.Path, ns.Path);
        Assert.Contains("/.namespaces/Demo.Greetings", ns.Path, StringComparison.Ordinal);
        Assert.Equal("Greeter.cs", file.Name);
        Assert.Equal(new FileInfo(Path.Combine(root, "src", "Demo", "Greeter.cs")).Length, file.SizeBytes);
        Assert.Equal(4, file.LineCount);
        Assert.Equal("SayHello", function.Name);
        Assert.StartsWith("qs-v1/dotnet/function/", function.Id, StringComparison.Ordinal);
    }

    [Fact]
    public void CuratedRulesUseGitWildmatchSemanticsAndSurfaceReasons()
    {
        CreateProject();
        WriteSource("src/Demo/Keep.cs");
        WriteSource("src/Demo/generated/Generated12.cs");
        WriteSource("src/Demo/generated/deep/GeneratedA2.cs");
        WriteSource("src/Demo/generated/deep/GeneratedABC.cs");
        Directory.CreateDirectory(Path.Combine(root, ".quality"));
        File.WriteAllText(Path.Combine(root, ".quality", "scope.json"), """
            {
              "rules": [
                { "action": "exclude", "pattern": "src/**/Generated[0-9A-Z]?.cs", "reason": "Generated fixture" }
              ]
            }
            """);

        var project = Assert.Single(RepositoryHierarchyBuilder.BuildDotNet(root));
        var module = Assert.Single(project.Children);
        var files = Files(module).Select(file => file.Path).ToArray();

        Assert.Contains("src/Demo/Keep.cs", files);
        Assert.Contains("src/Demo/generated/deep/GeneratedABC.cs", files);
        Assert.DoesNotContain("src/Demo/generated/Generated12.cs", files);
        Assert.DoesNotContain("src/Demo/generated/deep/GeneratedA2.cs", files);
        Assert.Equal(2, module.Exclusions.Count(item => item.Reason == "Generated fixture"));
    }

    [Fact]
    public void CuratedRulesOverrideGitIgnoreAndBuiltInDefaultsInOrder()
    {
        CreateProject();
        WriteSource("src/Demo/Keep.cs");
        WriteSource("src/Demo/ignored/Included.cs");
        WriteSource("src/Demo/Generated.g.cs");
        WriteSource("src/Demo/bin/Output.cs");
        WriteSource("src/Demo/AutoIncluded.cs", "// <auto-generated />\nnamespace Demo;");
        WriteSource("src/Demo/AutoExcluded.cs", "// <auto-generated />\nnamespace Demo;");
        File.WriteAllText(Path.Combine(root, ".gitignore"), "src/Demo/ignored\n");
        Directory.CreateDirectory(Path.Combine(root, ".quality"));
        File.WriteAllText(Path.Combine(root, ".quality", "scope.json"), """
            {
              "rules": [
                { "action": "include", "pattern": "src/Demo/ignored/Included.cs" },
                { "action": "include", "pattern": "src/Demo/Generated.g.cs" },
                { "action": "include", "pattern": "src/Demo/AutoIncluded.cs" },
                { "action": "exclude", "pattern": "src/Demo/Keep.cs", "reason": "Fixture excluded by repository policy" }
              ]
            }
            """);

        var module = Assert.Single(Assert.Single(RepositoryHierarchyBuilder.BuildDotNet(root)).Children);
        var files = Files(module).Select(file => file.Path).ToArray();

        Assert.Contains("src/Demo/ignored/Included.cs", files);
        Assert.Contains("src/Demo/Generated.g.cs", files);
        Assert.Contains("src/Demo/AutoIncluded.cs", files);
        Assert.DoesNotContain("src/Demo/Keep.cs", files);
        Assert.DoesNotContain("src/Demo/bin/Output.cs", files);
        Assert.DoesNotContain("src/Demo/AutoExcluded.cs", files);
        Assert.Contains(module.Exclusions, item => item.Path == "src/Demo/Keep.cs" && item.Reason == "Fixture excluded by repository policy");
        Assert.Contains(module.Exclusions, item => item.Path == "src/Demo/bin/Output.cs" && item.Reason == "Compiler build output");
        Assert.Contains(module.Exclusions, item => item.Path == "src/Demo/AutoExcluded.cs" && item.Reason == "Generated source");
    }

    [Fact]
    public void GitIgnoreNegationUsesLastMatchingRule()
    {
        CreateProject();
        WriteSource("src/Demo/ignored/Omit.cs");
        WriteSource("src/Demo/ignored/Keep.cs");
        File.WriteAllText(Path.Combine(root, ".gitignore"), "src/Demo/ignored/**\n!src/Demo/ignored/Keep.cs\n");

        var module = Assert.Single(Assert.Single(RepositoryHierarchyBuilder.BuildDotNet(root)).Children);

        Assert.Equal(["src/Demo/ignored/Keep.cs"], Files(module).Select(file => file.Path).ToArray());
        var exclusion = Assert.Single(module.Exclusions);
        Assert.Equal("src/Demo/ignored/Omit.cs", exclusion.Path);
        Assert.Contains(".gitignore:1", exclusion.Reason, StringComparison.Ordinal);
    }

    [Fact]
    public void RejectsCuratedExclusionWithoutReason()
    {
        CreateProject();
        WriteSource("src/Demo/Keep.cs");
        Directory.CreateDirectory(Path.Combine(root, ".quality"));
        File.WriteAllText(Path.Combine(root, ".quality", "scope.json"),
            "{\"rules\":[{\"action\":\"exclude\",\"pattern\":\"**/*.cs\"}]}");

        var exception = Assert.Throws<InvalidDataException>(() => RepositoryHierarchyBuilder.BuildDotNet(root));

        Assert.Contains("requires a non-empty reason", exception.Message, StringComparison.Ordinal);
    }

    private void CreateProject()
    {
        Directory.CreateDirectory(Path.Combine(root, "src", "Demo"));
        File.WriteAllText(Path.Combine(root, "Demo.slnx"),
            "<Solution><Project Path=\"src/Demo/Demo.csproj\" /></Solution>");
        File.WriteAllText(Path.Combine(root, "src", "Demo", "Demo.csproj"),
            "<Project Sdk=\"Microsoft.NET.Sdk\" />");
    }

    private void WriteSource(string relativePath, string content = "namespace Demo; internal sealed class Subject { }")
    {
        var path = Path.Combine(root, relativePath.Replace('/', Path.DirectorySeparatorChar));
        Directory.CreateDirectory(Path.GetDirectoryName(path)!);
        File.WriteAllText(path, content);
    }

    private static IEnumerable<HierarchyNode> Files(HierarchyNode module) =>
        module.Children.SelectMany(ns => ns.Children).Where(node => node.Level == ReviewLevel.File);

    public void Dispose()
    {
        if (Directory.Exists(root))
        {
            Directory.Delete(root, recursive: true);
        }

        GC.SuppressFinalize(this);
    }
}
